### ISSUE TITLE
Forbidden value, forbidden key and required key check cannot use a scope

### ISSUE THREAD

**Issue by jborgers** [sbaudoin/sonar-yaml#72]
Forbidden value and forbidden key can use regular expressions for the value and key resp., however, they cannot define a scope / (nested) dictionary where they should or should not be located.

Similarly, requiredKeyCheck can select for a parent key/value, however not for a scope/(nested)dictionary.

**Comment by jborgers** [comment]
I would suggest to use a regular expression for the scope. Example:

```
my-service:
  my-endpoint:
    connectionTimeout: 3000
```
we want to check if value < 1000 ms (violation when match \d\d\d\d) for such a key, however, not when it is defined as such:
```
spring:
  datasource:
    hikari:
      connectionTimeout: 5000
```
So, not when inside a scope containing 'hikari' or 'datasource'.

**Comment by jborgers** [comment]
Other example, 
```
resilience4j:
  circuitbreaker:
    minimumNumberOfCalls: 10
    failureRateThreshold: 50
    permittedNumberOfCallsInHalfOpenState: 2
    waitDurationInOpenState: 60
    slidingWindowSize: 20
    waitInterval: 30
```
We want to forbid the key 'waitInterval' because it is invalid and require the key 'waitDurationInOpenState'. Yet, we want to make sure this is checked only within resilience4j:circuitbreaker, preferable matching with a regex.

Furthermore, we like to do range checking for the property values, but maybe that is possible with regex already.
